FROM php:8.3

RUN apt-get update && apt-get install -y libpq-dev postgresql-client && \
  pecl install excimer && \
  docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
  docker-php-ext-install pdo_pgsql pgsql

WORKDIR /app
